### PR TITLE
Change: remove ruleset for block #openttd-logo-ipv6 from base.css

### PR DESCRIPTION
**Pull request by auge8472**
The namely ID is not in use anymore. There is no occurence of `#openttd-logo-ipv6` or `openttd-logo-ipv6` in the HTML, CSS or JS sources.

### CODE REVIEW

**Comment by LordAro** [comment]
Might as well delete the file at the same time

**Comment by auge8472** [comment]
> Might as well delete the file at the same time

Which file do you mean?

**Comment by LordAro** [comment]
`img/layout/openttd-64-ipv6.gif` the one referenced in the block ;)

**Comment by auge8472** [comment]
> 
> 
> `img/layout/openttd-64-ipv6.gif` the one referenced in the block ;)

Ah, didn't see the wood for the trees. Added a commit to remove the image.

**Comment by LordAro** [comment]
Urgh, silly CI failure. Squash the commits together to get it to rerun?

**Comment by auge8472** [comment]
> Urgh, silly CI failure. Squash the commits together to get it to rerun?

Done and "All checks have passed" :-)

**Pull request merged**
