### PR TITLE
General layout refactor

### PR DESCRIPTION
**Pull request by LordAro**
Refactors the site html, css & images to be more modern (not in looks, but code)

Seems to be mostly working

IANAWD (I am not a web developer)

### CODE REVIEW

**Comment by auge8472** [comment]
I am working on my own draft for a new HTML structure. As I can see, you tend to go into the same direction, but not so far as me. I want to open a similar PR with my own ideas, not for competition but for discussing and comparing ideas. Is that o.k. for you?

**Comment by LordAro** [comment]
Oooh, very interesting. I like what you've done, especially with the `<article>` usage and the lack-of-href in the nav. And perhaps more importantly (from a @TrueBrain perspective) your stuff is already split up into individual commits ^^
Given you've got most of the stuff that I have already (and a bit more), I think perhaps the best course of action would be for you to just take bits and pieces from this PR and apply it to yours? My changes thus far go a bit deeper in the CSS and changing the page structures

**Comment by TrueBrain** [comment]
Ping @LordAro : three tickets with near identical suggested changes, but no activity in a long time. What do you want to do with the pull requests?

**Comment by LordAro** [comment]
Closing this in preference to the many other PRs that have happened since

**Pull request closed without merging**
