### PR TITLE
Fix: make the size of the fast-download-header content aware

### PR DESCRIPTION
**Pull request by auge8472**
- Replace the background image of the fast-download-header with a semi transparent background colour with alpha channel (rgba system, [compatibility table on caniuse.com](https://caniuse.com/#feat=css3-colors)) and an invisible border to make corners rounded.
- Remove the width and height definitions of the block to allow an automatic resizing in case of a third text line (download link for beta or RC). 
- Cut the parcel from the original background image and set it into the left top corner of the block.

download header with two links
resized download header with three links

See #77 for discussion.

### CODE REVIEW

**Comment by LordAro** [comment]
This is similar to what I was planning on doing. download-fast.png should be deleted now? Or is it referenced somewhere else?

**Comment by auge8472** [comment]
> download-fast.png should be deleted now? Or is it referenced somewhere else?

I haven't searched for another reference. I will look through the code and will add another commit to remove the old background image if I doesn't find a further occurence.

**Comment by TrueBrain** [comment]
Hmm .. now the icon is not aligned with 3 lines (nitpicking ftw! :D) I guess this can be fixed with `#download-fast-3` setting the image on a slightly different place?

Would you mind terribly doing that? Otherwise my OCD would trigger every time we have a testing build available :D

PS: thank you so much for this! We have many more of these things to convert .. CSS came a long way in 10+ years, but our website did not ;)

**Comment by LordAro** [comment]
I "backported" my changes from my layout-refactor branch, looks OK to me?

**Pull request merged**
