### PR TITLE
Change: semantic HTML-elements for the pages main sections

### PR DESCRIPTION
**Pull request by auge8472**
… and corresponding CSS-rules

Further changes:

- remove background.png (replaced with CSS background-color)
- replace class name 'right' with 'further-link' because 'right' is based on the current optical represantation and with a change of that …

---

This is my third attempt to create an overhauled structure of the main page elements. After waiting for over a half year for the motivation to finish the work in #84 and struggling with importing the changes of the last seven months I decided to cherry-pick the old changes into a new branch and to finish the work on the requested change. I hope, these are all necessary parts.

### CODE REVIEW

**Comment by auge8472** [comment]
Building the website failed in the test because of an error, thrown in fetch-downloads.py (returned a non-zero code: 1). I didn't touch fetch-downloads.py and don't know how to handle the error. Any advice?

**Comment by glx22** [comment]
It's the usual random failure of downloads

**Comment by glx22** [comment]
Oh nice now the farm is totally broken

**Comment by TrueBrain** [comment]
Please rebase; that should fix the checks :)

**Comment by auge8472** [comment]
> Please rebase; that should fix the checks :)

You mean I should rebase my branch including your change of #114? Is that correct?

**Comment by LordAro** [comment]
That would have the effect of retriggering the CI, yes

**Comment by auge8472** [comment]
> 1 successful check

Yeah! :-)

**Comment by auge8472** [comment]
> Presuming removing background.png won't have a knock-on affect for the sub-sites not hosting their own...

Ha! I didn't check that. ...

As far as I can see, it is only the servers page/subdomain that uses the same layout in a copy? If so, the subdomain seems to use a copy of the image from the subdomain media.openttd.org (https://media.openttd.org/media/images/layout/background.png). The main page inserts the image directly from the domain www.openttd.org (https://www.openttd.org/static/img/layout/background.png).

It might be possible that one is a link to the other source on the file system of the server. But that's something I can't check. ;-)

**Comment by TrueBrain** [comment]
This repository is fully separate from the rest of the infrastructure. This includes reuse of images etc ;)

We used to host all images on media.openttd.org indeed (back in the days that was normal :P). So all the old infrastructure still uses that.

So yeah, this should be save to use :) Good analysis ;)

**Comment by TrueBrain** [comment]
https://www.staging.openttd.org/

Screenshots are aligned wrong now :( Not sure what went wrong :D

**Comment by auge8472** [comment]
> Screenshot on the homepage is aligned wrong now :( Not sure what went wrong :D

Is this cleared with #121?

**Comment by LordAro** [comment]
Indeed, should be fine now

**Comment by auge8472** [comment]
Thank you for the clarification. It's nice to see so many small but effectfull changes that followed during the last days. :+1:

**Pull request merged**
