### PR TITLE
Add: Mention some road vehicle sets for NRT.

### PR DESCRIPTION
**Pull request by stormcone**

### CODE REVIEW

**Comment by LordAro** [comment]
Not sure we want to advertise these just yet, those GRFs are very "unpolished"

**Comment by michicc** [comment]
Also, please start each sentence on a new line for Markdown files; gives better diffs.

**Comment by LordAro** [comment]
Merge conflict :>

**Comment by stormcone** [comment]
I think I need some help with how to squash the commits together. :(

**Comment by michicc** [comment]
I've just put that change in manually.

**Comment by stormcone** [comment]
@michicc Thank you. :)

**Pull request closed without merging**
