### PR TITLE
Fix overflowing nav

### PR DESCRIPTION
**Pull request by Milek7**
It makes it wider than content, but it looks better than now anyway..
Modified it to use flex layout too.

### CODE REVIEW

**Comment by TrueBrain** [comment]
This PR needs more context. "better than now anyway" is a vague statement. In the current version, on my OS and browser, I see no issues with the navigation. So please elaborate what you try to fix.

**Comment by Milek7** [comment]
obraz

**Comment by TrueBrain** [comment]
*holds hands*
OS? Browser? Version?
:)

**Comment by Milek7** [comment]
Firefox Developer Edition 72.0b10 and Chromium 79.0.3945.88 on Linux.
But I don't think this is any actionable information ;) I guess it is related to differences in font size rendering.

**Comment by LordAro** [comment]
I see it too, Arch Linux, Chromium (79) & Firefox (71). Might be something to do with the font loaded? - Trebuchet MS is requested, Chrome says it's loading DejaVu Sans

I'd still like to see a "better" solution that removes the need for the left/right navigation divs, but this will do for now.

**Comment by TrueBrain** [comment]
Now we are getting to the core of the issue :D

I guess Linux doesn't have `Trebuchet MS`, and the site was designed with that font in mind. Guess that would mean more things break :)

**Comment by Milek7** [comment]
Ok, widening wasn't necessary, just decreased minimum padding.
After fix:
obraz

**Comment by auge8472** [comment]
Playing the Advocatus Diaboli (the devils advocate):

> Ok, widening wasn't necessary, just decreased minimum padding.

That's o.k. in English language, it's o.k. with the intended font sizes and it's o.k., so long as noone want's to introduce translations of the UI with their different word lengths. If one of the assumtions failes, the navigation is vulnerable to overflow again.

*In the end* the site needs a contruction that is able to overflow without breaking design elements like the current background of the navigation.

**Pull request merged**
